# Starter pipeline

# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: agent1


steps:
- task: charleszipp.azure-pipelines-tasks-terraform.azure-pipelines-tasks-terraform-installer.TerraformInstaller@0
  displayName: 'Use Terraform latest'
- task: CmdLine@2
  inputs:
    script: 'terraform init'
- task: CmdLine@2
  inputs:
    script: |
      terraform plan
      terraform apply --auto-approve